/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/artist/$slug': typeof ArtistSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/artist/$slug': typeof ArtistSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services': typeof ServicesRoute
  '/artist/$slug': typeof ArtistSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/services' | '/artist/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services' | '/artist/$slug'
  id: '__root__' | '/' | '/services' | '/artist/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesRoute: typeof ServicesRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesRoute: ServicesRoute,
  ArtistSlugRoute: ArtistSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
